services:

  mail.event_listener.transaction_listener:
    class: MailBundle\Event\Listener\TransactionListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@mail.mailer.transaction_mailer'
#    tags:
#      - { name: kernel.event_listener, event: event.transaction.created, method: onTransactionCreated }