services:

  mail.mailer.abstract_mailer:
    class: MailBundle\Mailer\Mailer
    abstract: true
    arguments:
      - '@swiftmailer.mailer'
      - '@templating.engine.twig'

  mail.mailer.transaction_mailer:
    class: MailBundle\Mailer\TransactionMailer
    parent: mail.mailer.abstract_mailer
