<?php declare(strict_types=1);

namespace App\Command;

use App\Command\AbstractCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Routing\Router;
use Telegram\Bot\Api;

/**
 * Class SetWebHookCommand.
 */
class SetWebHookCommand extends AbstractCommand
{
    /** @var Api */
    private $telegram;
    /** @var string */
    private $url;

    protected function configure()
    {
        $this->setName('telegram:webhook:set')
            ->addArgument(
                'url',
                InputArgument::OPTIONAL,
                'the bot webhook uri, if not specified will be autogenerated',
                false
            );
    }

    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        parent::initialize($input, $output);

        $this->telegram = $this->getContainer()->get('app.service_telegram.telegram_client');
        $this->url = $this->in()->getArgument('url');
        if (!$this->url) {
            $this->url = $this->getContainer()->get('router')->generate('app_telegram_bot_hook', [
                'token' => $this->getContainer()->getParameter('telegram_hook_token')
            ], Router::ABSOLUTE_URL);
        }
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->out()->writeln(sprintf('Setting webhook on url %s', $this->url));

        $response = $this->telegram->setWebhook(['url' => $this->url]);

        $this->out()->writeln(sprintf('Webhook is : ', !$response->isError() ? 'ok' : 'unset'));
    }
}
