version: "3.4"

services:
  php:
    image: algatux/php-fpm-mongo:prod-1.2
    volumes:
        - ./:/home/php-user/project
    tty: true
    depends_on:
      - mysql
      - mongo
    container_name: dev_php
  nginx:
    image: nginx:1.13
    container_name: nginx
    volumes:
        - .:/home/php-user/project
        - ./docker/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
     - php
  mysql:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: dev-password
    volumes:
      - /var/docker/mysql:/var/lib/mysql
  mongo:
    image: mongo:3.4.2
    volumes:
      - /var/docker/mongo:/data/db
    entrypoint:
      - mongod
      - --storageEngine=wiredTiger
      - --bind_ip_all
