version: "3.3"

services:
  php:
    image: algatux/php-fpm-mongo:dev-1.2
    volumes:
        - ./:/home/php-user/project
    tty: true
    ports:
      - 9000:9000
    depends_on:
      - mysql
      - mongo
    container_name: dev_php
  nginx:
    image: nginx:1.13
    container_name: dev_nginx
    volumes:
        - .:/home/php-user/project
        - ./docker/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
     - php
  mysql:
    image: mysql:5.7.17
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev-password
  mongo:
    image: mongo:3.4.2
    ports:
      - 27017:27017
    entrypoint:
      - mongod
      - --quiet
      - --logpath=/dev/null
