version: "3.3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/prod/Dockerfile
    volumes:
        - ./:/home/php-user/project
    tty: true
    depends_on:
      - mysql
      - mongo
    container_name: prod_php
  nginx:
    image: nginx:1.13.1
    container_name: prod_nginx
    volumes:
        - .:/home/php-user/project
        - ./docker/nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
     - php
  mysql:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: dev-password
    volumes:
      - /home/php-user/mysql:/var/lib/mysql
  mongo:
    image: mongo:3.4.2
    volumes:
      - /home/php-user/mongo:/data/db
    entrypoint:
      - mongod
      - --auth
