imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: vendors/doctrine.yml }
    - { resource: vendors/mongodb.yml }
    - { resource: vendors/fos.yml }
    - { resource: vendors/assetic.yml }
    - { resource: vendors/sentry.yml }
    - { resource: vendors/flysystem.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    http_protocol: http

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: 2419200
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - BraincraftedBootstrapBundle:Form:bootstrap.html.twig

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    spool:     { type: memory }


