telegram:
    resource: "@TelegramBundle/Controller/"
    type:     annotation
    prefix:   /telegram

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_login_check:
    path: /api/login_check

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
