# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        telegram_webhook:
            pattern:  ^/telegram
            security: false

        api_login:
            pattern: ^/api/login$
            stateless: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path: api_jwt_login
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                remember_me: false
                post_only: true

        api_protected:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: ~

    access_control:
      - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
      - { path: ^/api/login_jwt, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%http_protocol%" }
