services:

  app.event_listener.transaction_listener:
    class: AppBundle\Event\Listener\TransactionListener
    arguments:
      - '@app.service_telegram.telegram_client'
      - '%telegram_group_id%'
    tags:
      - { name: kernel.event_listener, event: event.transaction.created, method: onTransactionCreated }
