services:

  AppBundle\Event\Listener\TelegramNotificationListener:
    class: AppBundle\Event\Listener\TelegramNotificationListener
    arguments:
      - '@app.amqp.message_publisher'
    tags:
      - { name: kernel.event_listener, event: event.transaction.created, method: onTransactionCreated }
