services:

  #TWIG
  app.twig_extension:
    class: AppBundle\Twig\AppBundleExtension
    public: false
    tags:
      - { name: twig.extension }

  # APPLICATION SERVICES
  app.service_wallet.wallet_persister:
    class: AppBundle\Service\Wallet\WalletPersister
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  app.service_transaction.transaction_persister:
    class: AppBundle\Service\Transaction\TransactionPersister
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  # STORAGES
  app.service_storage.transaction_storage:
    class: AppBundle\Service\Storage\TransactionStorage
    arguments:
      - '@oneup_flysystem.transactions_filesystem'

  # API
  app.service_serializer.api_serializer:
    class: AppBundle\Service\Serializer\ApiSerializer
