services:

  #TWIG
  app.twig_extension:
    class: AppBundle\Twig\AppBundleExtension
    public: false
    tags:
      - { name: twig.extension }

  # APPLICATION SERVICES
  app.service_wallet.wallet_persister:
    class: AppBundle\Service\Wallet\WalletPersister
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  app.service_transaction.transaction_persister:
    class: AppBundle\Service\Transaction\TransactionPersister
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'
